const rewire = require('rewire');
const png2teletext = rewire('../src/index');
const { TELETEXT_COLOR_BLACK } = require('../src/consts');
const generateColorMap = png2teletext.__get__('generateColorMap');
const assert = require('assert');
const fs = require('fs');
const { PNG } = require('pngjs');

const test1 = [
	[null, TELETEXT_COLOR_BLACK, TELETEXT_COLOR_BLACK, TELETEXT_COLOR_BLACK],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
	[
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
		TELETEXT_COLOR_BLACK,
	],
];

describe('generateColorMap', function() {
	it('should return with the correct colormap', function() {
		const data = fs.readFileSync('./test/test.png');
		const png = PNG.sync.read(data);
		const colorMap = generateColorMap(png.data, png.width);

		assert.deepStrictEqual(colorMap, test1);
	});
});
