export const TELETEXT_COLOR_BLACK = 0x10;
export const TELETEXT_COLOR_RED = 0x11;
export const TELETEXT_COLOR_GREEN = 0x12;
export const TELETEXT_COLOR_YELLOW = 0x13;
export const TELETEXT_COLOR_BLUE = 0x14;
export const TELETEXT_COLOR_MAGENTA = 0x15;
export const TELETEXT_COLOR_CYAN = 0x16;
export const TELETEXT_COLOR_WHITE = 0x17;
export const TELETEXT_EMPTY_CHARACTER = 0x20;

export const TELETEXT_CHARACTER_WIDTH = 2;
export const TELETEXT_CHARACTER_HEIGHT = 3;
export const NUMBER_OF_PNG_CHANNELS = 4;