'use strict';

const TELETEXT_COLOR_BLACK = 0x10;
const TELETEXT_COLOR_RED = 0x11;
const TELETEXT_COLOR_GREEN = 0x12;
const TELETEXT_COLOR_YELLOW = 0x13;
const TELETEXT_COLOR_BLUE = 0x14;
const TELETEXT_COLOR_MAGENTA = 0x15;
const TELETEXT_COLOR_CYAN = 0x16;
const TELETEXT_COLOR_WHITE = 0x17;
const TELETEXT_EMPTY_CHARACTER = 0x20;

const TELETEXT_CHARACTER_WIDTH = 2;
const TELETEXT_CHARACTER_HEIGHT = 3;
const NUMBER_OF_PNG_CHANNELS = 4;

module.exports = {
	TELETEXT_COLOR_BLACK,
	TELETEXT_COLOR_RED,
	TELETEXT_COLOR_GREEN,
	TELETEXT_COLOR_YELLOW,
	TELETEXT_COLOR_BLUE,
	TELETEXT_COLOR_MAGENTA,
	TELETEXT_COLOR_CYAN,
	TELETEXT_COLOR_WHITE,
	TELETEXT_EMPTY_CHARACTER,
	TELETEXT_CHARACTER_HEIGHT,
	TELETEXT_CHARACTER_WIDTH,
	NUMBER_OF_PNG_CHANNELS,
};
